### PR TITLE
Add Kaspersky TI 

### PR DESCRIPTION
**Pull request by AlexZilber**
Adds Kaspersky CyberTrace  to Tools, Kaspersky Threat Data Feeds to Sources and Kaspersky Threat Intelligence Portal  to Frameworks & Platforms

### CODE REVIEW

**Comment by AlexZilber** [comment]
@hslatman Hello! Do you have any questions about my commit?

**Comment by hslatman** [comment]
Hi @AlexZilber, 

I didn't; I simply didn't have the time to come to the repo.

I'm a little bit reluctant to add all three links, considering the fact that the last two of them are purely commercial. Have to admit: it does seem to be nice software 😄 

There are some more commercial links in the repo; the crept unto it over the course of time. I'm considering doing a bit of rework on the repo to indicate links as such.

Perhaps you could rewrite the main entry and casually link to the commercial offerings?

**Comment by markelovi** [comment]
Hi @hslatman,

Thank you for reply! Alexey and I understand that you would not want the page turned into an advertising resource due to the abundance of commercial products. We appealed to you precisely because we see that your page contains links to predominantly free products that can give value to non-commercial customers.
For our part, we are trying to develop products, the free functionality of which will be enough for the tasks of private researchers.
Alexey suggested adding descriptions for three of our TI-products. Let me comment each of them.

1. Feeds. 
I would like to emphasize that Kaspersky provides everyone with free access to our demo feeds. Although these feeds contain less information than commercial versions, their content still surpasses most OSINTs in number of indicators and quality of coverage.
I suggest changing the description text like this:

Kaspersky Threat Data Feeds
Kaspersky offers free demo Botnet C&C URL, Malicious Hash, and IP Reputation feeds to help all users to mitigate threats more effectively and defend against attacks even before they are launched.
For enterprises who are interested in Advanced Protection empowered by Threat Intelligence, Kaspersky provides continuously updated commercial Data Feeds that contain full sets of IoCs (hundreds times more compared to the demo ones) and are updated every few minutes.

2. Threat Intelligence Portal

Currently it's fully commercial product intended to support SOC use cases like incident triage or investigation. But I hope that in the nearest future we will offer for all users free version of this portal. So for now, I propose to remove this product from the list, but as soon as we have the free version ready, we would like to place its description on your page.

3. CyberTrace

This is a completely free product that allows to integrate our demo feeds, any third-party feeds in JSON, XML, STIX (incl TAXII), CSV and a number of OSINTs with the most popular SIEM solutions (a full list of supported systems is available here: https://support.kaspersky.com/datafeeds). While developing the product, we made a lot of efforts to make it useful for all our users, both commercial and non-commercial.
From my point of view, current description does not contains something like "commercial offering". May be we need just to note, that this tool is completely free and add a short manual how to download it:

Kaspersky CyberTrace
Threat intelligence fusion and analysis tool that integrates threat data feeds with SIEM solutions. Users can immediately leverage threat intelligence for security monitoring and incident report (IR) activities in the workflow of their existing security operations.
Kaspersky CyberTrace is available for free globally. To download Kaspersky CyberTrace, go to the Knowledge Base (https://support.kaspersky.com/datafeeds) and choose the solution that you are interested in integrating with. The links to download Kaspersky CyberTrace can be found on the page describing integration with your solution.

Are you agree with suggestions above? If it is ok for you, we will update the request.

Thank you in advance!
Ilya Markelov | Product Manager | Threat Management and Defense | Kaspersky Lab

**Comment by bslavin** [comment]
Thank you for the list, I am a commercial consumer of threat intelligence data and refer to your curated list quite often.  

I am very much in support of adding links to commercial feeds, it would be so valuable to have these resources located in one place. 

Right now we spend a lot of time trying to find feeds and did a providers that can benefit our product and users. @markelovi please feel free to reach out to me.

**Comment by hslatman** [comment]
I will have a look at determining a format to use in which paid as well as free sources have their place.

**Comment by hslatman** [comment]
I've merged it. Still planning to get back at some point to make clear which are commercial resources and which are not.

Thank you for your contributions and additional explanation, @markelovi. 

Keep up the good work!

**Pull request merged**
