### PR TITLE
Add link to Viper

### PR DESCRIPTION
**Pull request by krmaxwell**
Add a link to [Viper](http://viper.li), a malware library tool.

### CODE REVIEW

**Comment by sroberts** [comment]
Is that really threat intel? I know it's already on [awesome-malware-analysis](https://github.com/rshipp/awesome-malware-analysis).

**Comment by krmaxwell** [comment]
@sroberts Well, MISP is on there, so I figured it was in the same vein.

**Comment by krmaxwell** [comment]
Also: test failure is not related to this PR.

```
https://intel.criticalstack.com/ SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 
```

**Comment by hslatman** [comment]
I think I will go with @sroberts on this: to me Viper is closer to malware analysis than to threat indicators. It's certainly a tool that can be used for technical indicator input, but in that case there's a lot more tools in [awesome-malware-analysis](https://github.com/rshipp/awesome-malware-analysis) that can do similar things.

True for the test failures; testing links is rudimentary and it breaks on different kinds of SSL errors, timeouts, etcetera. I still think it's the best approach to checking that the referenced documents still exist and haven't moved, though.

**Pull request closed without merging**
