### PR TITLE
Add CrowdSec in README as a new source

### PR DESCRIPTION
**Pull request by mazzma12**

### CODE REVIEW

**Comment by mazzma12** [comment]
Hi @hslatman, is this repository still active ?

**Comment by hslatman** [comment]
It is! Not on a daily basis, though; I tend to merge in batches because of day job and other responsibilities. I think I can soon do another round.

**Comment by mazzma12** [comment]
I am glad to hear from you, I actually was wondering since the last commit was about 6months ago. I understand, everyone has duties :-)

**Comment by hslatman** [comment]
Thank you, @mazzma12! 😄

**Pull request merged**
