### PR TITLE
Add hashdd to README.md

### PR DESCRIPTION
**Pull request by pe3zx**
Add hashdd, a tool to lookup related information from crytographic hash value, to Tools section on `README.md`

### CODE REVIEW

**Comment by pe3zx** [comment]
Hey @hslatman, according to [build #302](https://travis-ci.org/hslatman/awesome-threat-intelligence/builds/289811570) ,what's your suggestion to deal with URL which has SSL/TLS error? Should it be on white listed URL or just modify awesome_bot to ignore SSL/TLS error?

Thanks!

**Comment by hslatman** [comment]
In many cases I add these to the ignored links, indeed. The bot is both a good and a bad thing. Sometimes it's SSL/TLS configurations that break the test, for example.

I hope to get to merging your PR soon. I want to know what happened to Animus before the merge. Seems they are gone, but I haven't gone deep on this one yet.

**Comment by hslatman** [comment]
I just realized that you mentioned to configure awesome_bot for SSL/TLS errors. I wasn't aware of that option yet; it think it would be the best way to handle these cases.

**Comment by hslatman** [comment]
Andrew Morris (@andrew-morris) seems to have been involved with Animus Intelligence. He's building some other awesome stuff (http://greynoise.io/) now; perhaps it makes use of (parts of) Omni. 

Will be merging this PR for now. I don't think Omni is coming back.

**Comment by andrew-morris** [comment]
Hey @hslatman, sorry about the confusion here. Unfortunately Animus + Omni had to go away (in name), but Grey Noise is the new continuation of that work. I haven't made up my mind on whether or not to bring back the log reducer, but I'll keep you posted. Thanks for your support!

**Pull request merged**
